<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffdrive">

		<!-- Gövde boyutları -->
		<xacro:property name="base_length" value="0.3"/>
		<xacro:property name="base_width" value="0.2"/>
		<xacro:property name="base_height" value="0.1"/>
		<xacro:property name="base_mass" value="1.0"/>

		<!-- Tekerlek boyutları -->
		<xacro:property name="wheel_radius" value="0.035"/>
		<xacro:property name="wheel_length" value="0.02"/>
		<xacro:property name="wheel_mass" value="0.2"/>
		<xacro:property name="wheel_separation" value="0.22"/>

		<!-- Caster boyutları -->
		<xacro:property name="caster_radius" value="0.02"/>
		<xacro:property name="caster_mass" value="0.1"/>

		<xacro:property name="update_rate" value="50.0"/>

		
		<!-- Linkler -->
		<link name="base_footprint"/>

		<link name="base_link">
			
			<visual>
				<origin xyz="0 0 0.03" rpy="0 0 0"/>
				<geometry>
					<box size="${base_length} ${base_width} ${base_height}"/>
				</geometry>
				<material name="blue">
					<color rgba="0 0 0.8 1"/>
				</material>
			</visual>
			
			<collision>
				<origin xyz="0 0 0.03" rpy="0 0 0"/>
				<geometry>
					<box size="${base_length} ${base_width} ${base_height}"/>
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0.03" rpy="0 0 0"/>
				<mass value="${base_mass}"/>
				<inertia ixx="0.00417" ixy="0" ixz="0" iyy="0.00833" iyz="0" izz="0.01083"/>
			</inertial>

		</link>

		<link name="left_wheel">

			<visual>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
				</geometry>
				<material name="blue">
					<color rgba="0 0 0.8 1"/>
				</material>
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${wheel_mass}"/>
				<inertia ixx="0.0000673" ixy="0" ixz="0" iyy="0.0000673" iyz="0" izz="0.0001225"/>
			</inertial>			

		</link>

		<link name="right_wheel">

			<visual>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
				</geometry>
				<material name="blue">
					<color rgba="0 0 0.8 1"/>
				</material>
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${wheel_mass}"/>
				<inertia ixx="0.0000673" ixy="0" ixz="0" iyy="0.0000673" iyz="0" izz="0.0001225"/>
			</inertial>			

		</link>

		<link name="caster_link">

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<sphere radius="${caster_radius}"/>
				</geometry>
				<material name="blue">
					<color rgba="0 0 0.8 1"/>
				</material>
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<sphere radius="${caster_radius}"/>
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${caster_mass}"/>
				<inertia ixx="0.000016" ixy="0" ixz="0" iyy="0.000016" iyz="0" izz="0.000016"/>
			</inertial>			

		</link>

		
		<!-- Jointler -->
		<joint name="base_footprint_joint" type="fixed">
			
			<parent link="base_footprint"/>
			<child link="base_link"/>
			<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>

		</joint>

		<joint name="left_wheel_joint" type="continuous">
			
			<parent link="base_link"/>
			<child link="left_wheel"/>
			<origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>

		</joint>

		<joint name="right_wheel_joint" type="continuous">
			
			<parent link="base_link"/>
			<child link="right_wheel"/>
			<origin xyz="0 ${-wheel_separation/2} 0" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>

		</joint>

		<joint name="caster_joint" type="fixed">

			<parent link="base_link"/>
			<child link="caster_link"/>
			<origin xyz="${base_length/2 - caster_radius} 0 ${-(wheel_radius - caster_radius)}" rpy="0 0 0"/>

		</joint>


		<!-- Gazebo Tagleri -->
		<gazebo reference="base_link">
			<material>Gazebo/Blue</material>
		</gazebo>

		<gazebo reference="left_wheel">
			<material>Gazebo/Black</material>
		</gazebo>

		<gazebo reference="right_wheel">
			<material>Gazebo/Black</material>
		</gazebo>

		<gazebo reference="caster_link">
			<mu1>0</mu1>
			<mu2>0</mu2>
			<material>Gazebo/Grey</material>
		</gazebo>


		<!-- Gazebo Differential Drive Plugini -->
		<gazebo>
			<plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
				<ros>
					<namespace>/</namespace>
				</ros>
				<left_joint>left_wheel_joint</left_joint>
				<right_joint>right_wheel_joint</right_joint>
				<wheel_separation>${wheel_separation}</wheel_separation>
				<wheel_diameter>${wheel_radius * 2}</wheel_diameter>
				<command_topic>cmd_vel</command_topic>
				<publish_odom>true</publish_odom>
				<publish_odom_tf>true</publish_odom_tf>
				<odometry_frame>odom</odometry_frame>
				<robot_base_frame>base_footprint</robot_base_frame>
				<update_rate>${update_rate}</update_rate>
			</plugin>
		</gazebo>

</robot>